### ISSUE TITLE
Suggestion: Multi-Level sorting with tables containing much data

### ISSUE THREAD

**Issue by merlinuwe** [kraibse/obsidian-table-sorting#2]
As mentioned in Reddit, I'd like to sort not only by one column at a time, but by all of them.

If the table is sorted by a column, this sorting should be the base for the next sort of an other column. It should not sort always the original table order again.

The sorting has to be stored between Obsidian sessions.

I mean a sorting like in Excel.

**Comment by kraibse** [comment]
I think I've grasped [the concept](https://www.microsoft.com/en-us/videoplayer/embed/RWfzt5?pid=ocpVideo1-innerdiv-oneplayer&postJsllMsg=true&maskLevel=20&reporting=true&market=en-us) of having multiple levels to sort by. Let me see what I can do.
