### ISSUE TITLE
Plugin Installation Broken

### ISSUE THREAD

**Issue by ChilledCosmonaut** [kraibse/obsidian-table-sorting#21]
## Issue Description

Installing the PLugin according to the ReadMe.md yields a non activatable plugin.

## Steps to Reproduce

1. Download git repo as zip file
2. Unpack it
3. Move the main.ts, style.css and mainfest.json into the folder
4. Obsidian yields error on activation

**Comment by ChilledCosmonaut** [comment]
Sorry. Release actually works....

**Comment by kraibse** [comment]
I've included all the files necessary for installation in the latest release. Obsidian needs the `main.js` and not the `main.ts` file in addition to the `manifest.json` and the `styles.css` files.

From then on it should work as intended.
