### ISSUE TITLE
Can't install through BRAT

### ISSUE THREAD

**Issue by Kullenej** [kraibse/obsidian-table-sorting#24]
## Issue Description

Whenever plugins isn't in the community store, I install them through BRAT. When I try to do that, it tells me that main.js is missing. I see that you have named it main.ts. Is it possible to change that?

**Comment by kraibse** [comment]
As far as I know the BRAT plugin uses the releases to get the needed files. For now, you should be able to add this plugin with the frozen version `1.4.0` by using the link to [the v1.4.0 release](https://github.com/kraibse/obsidian-table-sorting/releases/tag/1.4.0).

I'll look into some other plugins that can be easily installed with BRAT to solve the issue.

Also, going by the provided .gitignore, Obsidian doesn't intend devs to upload the compiled main.js in the repository. Still, I'm going to look into it.

**Comment by kraibse** [comment]
My personal vault just updated the extension. It was an issue with the release tagging. Please confirm that the issue does not persist anymore on your side.
