### ISSUE TITLE
This messes with the calendar plugin

### ISSUE THREAD

**Issue by FearTheBadger** [kraibse/obsidian-table-sorting#4]
Apparently the calendar plugin uses a giant table. This plugin has made it so the children like me quickly screwed up the look of the calendar, in such a way that I can't get it back without closing the application.

![calendar](https://user-images.githubusercontent.com/3730852/218533733-2d8513ad-b55c-470e-a112-b1c8281bd945.JPG)

**Comment by FearTheBadger** [comment]
(btw I just wanted to say, thank you for this plugin. It is wonderful to have sorting in the hybrid editing mode.)

**Comment by kraibse** [comment]
Thanks for the feedback! Can you link the exact plugin you're using? I'll get to it as soon as I can.

**Comment by kraibse** [comment]
Report back to me with your testing results. Hoping for your feedback whenever you notice any bugs :)
